version: '3'

services:
  back-example:
    build: 
      dockerfile: Dockerfile
      context: ./examples/example/
    ports:
      - 3001:3001
  web:
    build:
      dockerfile: Dockerfile
      context: ./web
    ports:
      - 8080:80